server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: WeLearnApp
  datasource:
    url: jdbc:mysql://localhost:3306/welearn_db
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

application-init:
  admin:
    username: admin
    password: Admin123
    email: admin@gmail.com

jwt:
  signer-key:
    access: koQXz++/f0WDkcQ008UNOxjNWehl9aYjsNZgyefXWtP5XRdWmBwOYMXZeGaOACqU
    refresh: muJHr4ajU1eRCTJQpfP5+hkwx5WC6t7GHr7bVUcyWP8bq6Dcl8AuXrv4+ZqhKzQq
  duration:
    access: 3600
    refresh: 86400

message:
  controller:
    authentication:
      logout-success: "Logout successfully"
    role:
      delete-success: "Role deleted successfully"
    learning-session:
      delete-success: "Learning session deleted successfully"

verification-code:
  duration: 5 # in minutes
  length: 6

mail:
  api-key: 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
  sender:
    email: nqt460@gmail.com
    name: "WeLearn Team"

# Used in data migration
NODE_ENV: development
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_USERNAME: root
MYSQL_PASSWORD: root
MYSQL_DATABASE: welearn_db
