server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${CONTEXT_PATH}

spring:
  application:
    name: WeLearnApp
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER_CLASSNAME}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

application-init:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
    email: ${ADMIN_EMAIL}

jwt:
  signer-key:
    access: ${AC_SIGNER_KEY}
    refresh: ${RF_SIGNER_KEY}
    update-unverified-email: ${UPDATE_UNVERIFIED_EMAIL_SIGNER_KEY}
  duration:
    access: ${AC_DURATION}
    refresh: ${RF_DURATION}
    update-unverified-email: ${UPDATE_UNVERIFIED_EMAIL_DURATION}

message:
  controller:
    authentication:
      logout-success: "Logout successfully"
    user:
      update-unverified-email-success: "Email updated successfully. Please check your email to verify the new email address"
    role:
      delete-success: "Role deleted successfully"
    learning-session:
      delete-success: "Learning session deleted successfully"
    order:
      cancel-success: "Order canceled successfully"

verification-code:
  duration: ${VC_DURATION} # in minutes
  length: ${VC_LENGTH}

mail:
  api-key: ${MAIL_API_KEY}
  sender:
    email: ${MAIL_SENDER_EMAIL}
    name: ${MAIL_SENDER_NAME}

payment:
  vnp:
    vnp-version: ${VNP_VERSION}
    vnp_command: ${VNP_COMMAND}
    tmn-code: ${VNP_TMN_CODE}
    vnp-CurrCode: ${VNP_CURR_CODE}
    vnp-Locale: ${VNP_LOCALE}
    vnp-OrderInfo: ${VNP_ORDER_INFO}
    vnp-OrderType: ${VNP_ORDER_TYPE}
    vnp-ReturnUrl: ${VNP_RETURN_URL}
    vnp-ExpireDuration: ${VNP_EXPIRE_DURATION} # in minutes
    hash-secret: ${VNP_HASH_SECRET}
    url: ${VNP_URL}
    vnp-success-code: ${VNP_SUCCESS_CODE}
    client-payment-success-url: ${CLIENT_PAYMENT_SUCCESS_URL}